Web3,sln: remove some unneeded constructors & projects & sols
We're getting a strange MethodNotFoundException in Sentry[1]:

MissingMethodException: Method not found: void Nethereum.Web3.Web3..ctor(System.TimeSpan,string,Common.Logging.ILog,System.Net.Http.Headers.AuthenticationHeaderValue)
  Module "GWallet.Backend.Ether.Server", line 86, col 0, in Web3Server
    GWallet.Backend.Ether.SomeWeb3 Web3Server(System.TimeSpan, GWallet.Backend.ServerDetails)
  Module "GWallet.Backend.Ether.Server+Web3ServerToRetrievalFunc@402[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]", line 0, col 0, in Invoke
    Microsoft.FSharp.Control.FSharpAsync`1[System.Decimal] Invoke(Microsoft.FSharp.Core.Unit)
  Module "Microsoft.FSharp.Control.AsyncPrimitives", line 5, col 0, in CallThenInvoke
    Microsoft.FSharp.Control.AsyncReturn CallThenInvoke[Decimal,Unit](Microsoft.FSharp.Control.AsyncActivation`1[System.Decimal], Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FSharpAsync`1[System.Decimal]])
  Module "Microsoft.FSharp.Control.Trampoline", line 32, col 0, in Execute
    Microsoft.FSharp.Control.AsyncReturn Execute(Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn])

Maybe removing the constructors we don't use we will workaround the
problem? (But we had to remove projects from the main solution, and
unneeded solutions, which depended on these ctors; oh well, at least
we don't need these projects...)

[1] https://sentry.io/organizations/nblockchain/issues/2158262874/?project=187797